packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - esbuild
  - prisma
  - tree-sitter
  - tree-sitter-json
